
#ifndef CPPBUFFER_USES_ASSERT
#define CPPBUFFER_USES_ASSERT 1
#endif

#ifndef CPPBUFFER_ASSERT_USES_CASSERT
#define CPPBUFFER_ASSERT_USES_CASSERT 0
#endif

#ifndef CPPBUFFER_ASSERT_USES_EXCEPTIONS
#define CPPBUFFER_ASSERT_USES_EXCEPTIONS 1
#endif
